### ISSUE TITLE
Sync work tree changes after web update

### ISSUE THREAD

**Issue by ericemmrich** [Rynoxx/ispconfig3-website-git#3]
Hi,

first of all I'd like to thank you for this awesome plugin! I set it up today and now wondered whether it's possible to sync any changes that were made in the /web/ root with the Git repo (e.g. after a WordPress plugin update from the WP admin area)?

Many thanks in advance.

**Comment by ericemmrich** [comment]
Found the solution myself. If anyone is interested, it can be done with a one liner:

`cd ~ && git --git-dir=/website.git --work-tree=/web add /web/. && git --git-dir=/website.git --work-tree=/web commit -a -m "File changes after web update"`

The above command assumes Jailkit as the chroot environment. If NONE is used, replace all path names with the absolute path (just like in the usage example).

**Comment by Rynoxx** [comment]
Thanks! I've updated the readme to include your instructions for committing local changes :slightly_smiling_face:
